### ISSUE TITLE
Allow first CPro push to come from plugin

### ISSUE THREAD

**Issue by tooky** [cucumber-ltd/cucumber-pro-plugin-jvm#9]
When I was setting up the plugin for Shouty on circle I hadn't pushed any docs to CPro. I was expecting the git publisher in the plugin to allow this.

It didn't fail the build, but this output from Git was in the [build output](https://circleci.com/gh/cucumber-ltd/shouty.java/7):

```
error: Could not read 6b747f2d8eb3e3072afb692a6e48e57328976a08
fatal: Failed to traverse parents of commit eb681ff9b5a58a40eb9427170a22c04432ea5051
error: Could not read 6b747f2d8eb3e3072afb692a6e48e57328976a08
fatal: Failed to traverse parents of commit eb681ff9b5a58a40eb9427170a22c04432ea5051

Published documentation to Cucumber Pro: git@git.cucumber.pro:shouty.java.git
```

I think it may be related to the bare repo, and how circle clones the repo from Github.

**Comment by aslakhellesoy** [comment]
I think this is because Circle only performs a _shallow clone_ of the repo, which only pulls down the latest n commits of the repo’s history. The reason it's doing that is that it's faster.

The plugin could try to detect the error seen above, fetch all the commits if it happens, and then try the push again.
